DEBUG 2021-04-08 03:32:44.603 UTC: 	 CRAB Client version: v3.210127
DEBUG 2021-04-08 03:32:44.603 UTC: 	 Running on: Linux lxplus736.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-08 03:32:44.603 UTC: 	 Executing command: 'status'
DEBUG 2021-04-08 03:32:44.604 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bharikri/.crab3
ERROR 2021-04-08 03:32:44.606 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bharikri/private/TopLFV/CMSSW_10_6_4/src/PhysicsTools/NanoAODTools/crab/CRABtasks/crab_NanoLFVtest_Apr7_2017_TTZToQQ
ERROR 2021-04-08 03:32:44.606 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/SubCommand.py", line 643, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/SubCommand.py", line 505, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bharikri/private/TopLFV/CMSSW_10_6_4/src/PhysicsTools/NanoAODTools/crab/CRABtasks/crab_NanoLFVtest_Apr7_2017_TTZToQQ
INFO 2021-04-08 03:32:44.611 UTC: 	 Log file is /afs/cern.ch/user/b/bharikri/private/TopLFV/CMSSW_10_6_4/src/PhysicsTools/NanoAODTools/crab/crab.log
